name: bpref
channels:
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch=1.4.0
  - numpy=1.19.5        # Required for MuJoCo-compatible dm_control
  - matplotlib          # Compatible with numpy 1.19
  - absl-py
  - pyparsing
  - pip
  - pip:
      - termcolor
      - tb-nightly==2.4.0a20210301    
      - imageio
      - imageio-ffmpeg
      - git+https://github.com/facebookresearch/hydra@0.11_branch
      - glfw==1.11.2
      - scikit-image==0.18.3          # Last version supporting numpy 1.19
      - gym==0.21.0                   # Last Gym version using old API
      - cached-property
      - mako
      - pygame
      - python-dateutil
      - scipy==1.10.1
      - joblib

